#!/bin/bash

http_proxy_install(){
	echo "Performing http proxy installation"
	ln -sf "../backends-available/proxy.conf" "conf.d/l2.conf"
	return 0
}

http_fastcgi_install(){
	echo "Performing fastcgi installation"
	ln -sf "../backends-available/fastcgi.conf" "conf.d/l2.conf"
	cp contrib/phpfcgi.service /etc/systemd/system/phpfcgi.service
	return 0
}

citrix_install(){
	echo "Performing citrix installation"
	ln -sf "../backends-available/proxy.conf" "conf.d/l2.conf"
	ln -sf "../snippets/citrix-session.conf" "snippets-enabled/citrix-session.conf"
	return 0
}

declare -A installers=( 
	[proxy]=http_proxy_install
	[fastcgi]=http_fastcgi_install
	[citrix]=citrix_install
)

read -p "Performing new installation proceed [y/N] " -n 1 choose
if [[ $choose =~ ^[Nn]*$ ]]
then
	echo "cowardly refusing to perform installation"
	exit 1
fi

echo ""
#echo '' > install.log

service="$( systemctl status nginx | grep Loaded | awk '{ print $3 }' | sed -E "s/^[(]//" | sed -E "s/;$//" )"
if [ -z "$service" ]; then
	echo "Failed to obtain global nginx service file location"
	exit 2
fi

sdir="$( nginx -V |& grep -Eo "prefix=[^ ]+" | sed "s/prefix=//" )"
if [ -z "$sdir" ]; then
	echo "Failed to obtain nginx configuration directory"
	exit 3
fi

if [ ! -w "$sdir" ]; then
	echo "nginx configuration directory is not writeable by current user"
	exit 4
fi

cp -rf {bin,backends-available,conf.d,html,nginx.conf,README.md} $sdir &>> install.log

if [ ! -w "/etc/systemd/system" ]; then
	echo "local systemd directory is not writeable by current user"
	exit 5
fi

cp -f "$service" /etc/systemd/system &>> install.log

if [ -z "$( cat /etc/systemd/system/nginx.service | grep ExecStartPre=/etc/nginx/bin/execstartpre )" ]; then
	ln="$( cat /usr/lib/systemd/system/nginx.service | grep -nE "ExecStart" | grep -Eo "^[0-9]+" )"
	sed -i "${ln}i ExecStartPre=/etc/nginx/bin/execstartpre" /etc/systemd/system/nginx.service &>> install.log
fi

$sdir/bin/createdirs &>> install.log || { echo "Failed to create nginx runtime directories"; exit 5; }
instkeys=( ${!installers[@]} )

while :
do
	i=1
	echo "Please select a backend:"
	for backend in "${!installers[@]}"
	do
		echo "$i) $backend"
		((i=i+1))
	done
	((i=i-1))
	read -p "Please enter backend number from 1-$i: " selected
		
	if [ $selected -ge 1 ] && [ $selected -le $i ]; then
		((selected=selected-1))
		${installers[${instkeys[$selected]}]}
		break
	else
		echo "Invalid choice"
	fi
done
